export const ACCOUNTANT_REGISTER_REQUEST = 'ACCOUNTANT_REGISTER_REQUEST'
export const ACCOUNTANT_REGISTER_SUCCESS = 'ACCOUNTANT_REGISTER_SUCCESS'
export const ACCOUNTANT_REGISTER_FAIL = 'ACCOUNTANT_REGISTER_FAIL'

// Constants for fetching all accountants
export const ACCOUNTANT_LIST_REQUEST = 'ACCOUNTANT_LIST_REQUEST';
export const ACCOUNTANT_LIST_SUCCESS = 'ACCOUNTANT_LIST_SUCCESS';
export const ACCOUNTANT_LIST_FAIL = 'ACCOUNTANT_LIST_FAIL';

// Constants for fetching single accountant details
export const ACCOUNTANT_DETAILS_REQUEST = 'ACCOUNTANT_DETAILS_REQUEST';
export const ACCOUNTANT_DETAILS_SUCCESS = 'ACCOUNTANT_DETAILS_SUCCESS';
export const ACCOUNTANT_DETAILS_FAIL = 'ACCOUNTANT_DETAILS_FAIL';

// Constants for updating accountant
export const ACCOUNTANT_UPDATE_REQUEST = 'ACCOUNTANT_UPDATE_REQUEST';
export const ACCOUNTANT_UPDATE_SUCCESS = 'ACCOUNTANT_UPDATE_SUCCESS';
export const ACCOUNTANT_UPDATE_FAIL = 'ACCOUNTANT_UPDATE_FAIL';
export const ACCOUNTANT_UPDATE_RESET = 'ACCOUNTANT_UPDATE_RESET';

// Constants for deleting accountant
export const ACCOUNTANT_DELETE_REQUEST = 'ACCOUNTANT_DELETE_REQUEST';
export const ACCOUNTANT_DELETE_SUCCESS = 'ACCOUNTANT_DELETE_SUCCESS';
export const ACCOUNTANT_DELETE_FAIL = 'ACCOUNTANT_DELETE_FAIL';

// Constants for resetting accountant data states
export const ACCOUNTANT_RESET = 'ACCOUNTANT_RESET';