export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'

// Fetch comments by lead ID
export const FETCH_COMMENTS_BY_LEAD_REQUEST = 'FETCH_COMMENTS_BY_LEAD_REQUEST';
export const FETCH_COMMENTS_BY_LEAD_SUCCESS = 'FETCH_COMMENTS_BY_LEAD_SUCCESS';
export const FETCH_COMMENTS_BY_LEAD_FAIL = 'FETCH_COMMENTS_BY_LEAD_FAIL';

// Fetch comments by agent ID
export const FETCH_COMMENTS_BY_AGENT_REQUEST = 'FETCH_COMMENTS_BY_AGENT_REQUEST';
export const FETCH_COMMENTS_BY_AGENT_SUCCESS = 'FETCH_COMMENTS_BY_AGENT_SUCCESS';
export const FETCH_COMMENTS_BY_AGENT_FAIL = 'FETCH_COMMENTS_BY_AGENT_FAIL';

// Fetch all comments
export const FETCH_ALL_COMMENTS_REQUEST = 'FETCH_ALL_COMMENTS_REQUEST';
export const FETCH_ALL_COMMENTS_SUCCESS = 'FETCH_ALL_COMMENTS_SUCCESS';
export const FETCH_ALL_COMMENTS_FAIL = 'FETCH_ALL_COMMENTS_FAIL';

// Constants for fetching today's comments by agent
export const FETCH_MY_TODAYS_COMMENTS_REQUEST = 'FETCH_MY_TODAYS_COMMENTS_REQUEST';
export const FETCH_MY_TODAYS_COMMENTS_SUCCESS = 'FETCH_MY_TODAYS_COMMENTS_SUCCESS';
export const FETCH_MY_TODAYS_COMMENTS_FAIL = 'FETCH_MY_TODAYS_COMMENTS_FAIL';

export const FETCH_ALL_TODAYS_COMMENTS_REQUEST = 'FETCH_ALL_TODAYS_COMMENTS_REQUEST';
export const FETCH_ALL_TODAYS_COMMENTS_SUCCESS = 'FETCH_ALL_TODAYS_COMMENTS_SUCCESS';
export const FETCH_ALL_TODAYS_COMMENTS_FAIL = 'FETCH_ALL_TODAYS_COMMENTS_FAIL';