export const FETCH_INCIDENTS_REQUEST = 'FETCH_INCIDENTS_REQUEST';
export const FETCH_INCIDENTS_SUCCESS = 'FETCH_INCIDENTS_SUCCESS';
export const FETCH_INCIDENTS_FAILURE = 'FETCH_INCIDENTS_FAILURE';

export const SUBMIT_EXTERNAL_EXAM_FORM_REQUEST = 'SUBMIT_EXTERNAL_EXAM_FORM_REQUEST';
export const SUBMIT_EXTERNAL_EXAM_FORM_SUCCESS = 'SUBMIT_EXTERNAL_EXAM_FORM_SUCCESS';
export const SUBMIT_EXTERNAL_EXAM_FORM_FAILURE = 'SUBMIT_EXTERNAL_EXAM_FORM_FAILURE';

export const SUBMIT_SPECIAL_EXAM_FORM_REQUEST = 'SUBMIT_SPECIAL_EXAM_FORM_REQUEST';
export const SUBMIT_SPECIAL_EXAM_FORM_SUCCESS = 'SUBMIT_SPECIAL_EXAM_FORM_SUCCESS';
export const SUBMIT_SPECIAL_EXAM_FORM_FAILURE = 'SUBMIT_SPECIAL_EXAM_FORM_FAILURE';

export const SUBMIT_SUPPLEMENTARY_FORM_REQUEST = 'SUBMIT_SUPPLEMENTARY_FORM_REQUEST';
export const SUBMIT_SUPPLEMENTARY_FORM_SUCCESS = 'SUBMIT_SUPPLEMENTARY_FORM_SUCCESS';
export const SUBMIT_SUPPLEMENTARY_FORM_FAILURE = 'SUBMIT_SUPPLEMENTARY_FORM_FAILURE';

// Constants for fetching all external exam applications
export const FETCH_ALL_EXTERNAL_EXAMS_REQUEST = 'FETCH_ALL_EXTERNAL_EXAMS_REQUEST';
export const FETCH_ALL_EXTERNAL_EXAMS_SUCCESS = 'FETCH_ALL_EXTERNAL_EXAMS_SUCCESS';
export const FETCH_ALL_EXTERNAL_EXAMS_FAILURE = 'FETCH_ALL_EXTERNAL_EXAMS_FAILURE';

// Constants for fetching a single external exam application
export const FETCH_EXTERNAL_EXAM_REQUEST = 'FETCH_EXTERNAL_EXAM_REQUEST';
export const FETCH_EXTERNAL_EXAM_SUCCESS = 'FETCH_EXTERNAL_EXAM_SUCCESS';
export const FETCH_EXTERNAL_EXAM_FAILURE = 'FETCH_EXTERNAL_EXAM_FAILURE';

// Constants for updating an external exam application
export const UPDATE_EXTERNAL_EXAM_REQUEST = 'UPDATE_EXTERNAL_EXAM_REQUEST';
export const UPDATE_EXTERNAL_EXAM_SUCCESS = 'UPDATE_EXTERNAL_EXAM_SUCCESS';
export const UPDATE_EXTERNAL_EXAM_FAILURE = 'UPDATE_EXTERNAL_EXAM_FAILURE';

// Constants for deleting an external exam application
export const DELETE_EXTERNAL_EXAM_REQUEST = 'DELETE_EXTERNAL_EXAM_REQUEST';
export const DELETE_EXTERNAL_EXAM_SUCCESS = 'DELETE_EXTERNAL_EXAM_SUCCESS';
export const DELETE_EXTERNAL_EXAM_FAILURE = 'DELETE_EXTERNAL_EXAM_FAILURE';


// Constants for fetching all special exam applications
export const FETCH_ALL_SPECIAL_EXAMS_REQUEST = 'FETCH_ALL_SPECIAL_EXAMS_REQUEST';
export const FETCH_ALL_SPECIAL_EXAMS_SUCCESS = 'FETCH_ALL_SPECIAL_EXAMS_SUCCESS';
export const FETCH_ALL_SPECIAL_EXAMS_FAILURE = 'FETCH_ALL_SPECIAL_EXAMS_FAILURE';

// Constants for fetching a single special exam application
export const FETCH_SPECIAL_EXAM_REQUEST = 'FETCH_SPECIAL_EXAM_REQUEST';
export const FETCH_SPECIAL_EXAM_SUCCESS = 'FETCH_SPECIAL_EXAM_SUCCESS';
export const FETCH_SPECIAL_EXAM_FAILURE = 'FETCH_SPECIAL_EXAM_FAILURE';

// Constants for updating a special exam application
export const UPDATE_SPECIAL_EXAM_REQUEST = 'UPDATE_SPECIAL_EXAM_REQUEST';
export const UPDATE_SPECIAL_EXAM_SUCCESS = 'UPDATE_SPECIAL_EXAM_SUCCESS';
export const UPDATE_SPECIAL_EXAM_FAILURE = 'UPDATE_SPECIAL_EXAM_FAILURE';

// Constants for deleting a special exam application
export const DELETE_SPECIAL_EXAM_REQUEST = 'DELETE_SPECIAL_EXAM_REQUEST';
export const DELETE_SPECIAL_EXAM_SUCCESS = 'DELETE_SPECIAL_EXAM_SUCCESS';
export const DELETE_SPECIAL_EXAM_FAILURE = 'DELETE_SPECIAL_EXAM_FAILURE';

// Constants for fetching all supplementary exam applications
export const FETCH_ALL_SUPPLEMENTARY_EXAMS_REQUEST = 'FETCH_ALL_SUPPLEMENTARY_EXAMS_REQUEST';
export const FETCH_ALL_SUPPLEMENTARY_EXAMS_SUCCESS = 'FETCH_ALL_SUPPLEMENTARY_EXAMS_SUCCESS';
export const FETCH_ALL_SUPPLEMENTARY_EXAMS_FAILURE = 'FETCH_ALL_SUPPLEMENTARY_EXAMS_FAILURE';

// Constants for fetching a single supplementary exam application
export const FETCH_SUPPLEMENTARY_EXAM_REQUEST = 'FETCH_SUPPLEMENTARY_EXAM_REQUEST';
export const FETCH_SUPPLEMENTARY_EXAM_SUCCESS = 'FETCH_SUPPLEMENTARY_EXAM_SUCCESS';
export const FETCH_SUPPLEMENTARY_EXAM_FAILURE = 'FETCH_SUPPLEMENTARY_EXAM_FAILURE';

// Constants for updating a supplementary exam application
export const UPDATE_SUPPLEMENTARY_EXAM_REQUEST = 'UPDATE_SUPPLEMENTARY_EXAM_REQUEST';
export const UPDATE_SUPPLEMENTARY_EXAM_SUCCESS = 'UPDATE_SUPPLEMENTARY_EXAM_SUCCESS';
export const UPDATE_SUPPLEMENTARY_EXAM_FAILURE = 'UPDATE_SUPPLEMENTARY_EXAM_FAILURE';

// Constants for deleting a supplementary exam application
export const DELETE_SUPPLEMENTARY_EXAM_REQUEST = 'DELETE_SUPPLEMENTARY_EXAM_REQUEST';
export const DELETE_SUPPLEMENTARY_EXAM_SUCCESS = 'DELETE_SUPPLEMENTARY_EXAM_SUCCESS';
export const DELETE_SUPPLEMENTARY_EXAM_FAILURE = 'DELETE_SUPPLEMENTARY_EXAM_FAILURE';
