// Fee structure constants
export const CREATE_FEE_STRUCTURE_REQUEST = 'CREATE_FEE_STRUCTURE_REQUEST';
export const CREATE_FEE_STRUCTURE_SUCCESS = 'CREATE_FEE_STRUCTURE_SUCCESS';
export const CREATE_FEE_STRUCTURE_FAIL = 'CREATE_FEE_STRUCTURE_FAIL';

export const GET_ALL_FEE_STRUCTURES_REQUEST = 'GET_ALL_FEE_STRUCTURES_REQUEST';
export const GET_ALL_FEE_STRUCTURES_SUCCESS = 'GET_ALL_FEE_STRUCTURES_SUCCESS';
export const GET_ALL_FEE_STRUCTURES_FAIL = 'GET_ALL_FEE_STRUCTURES_FAIL';

export const GET_FEE_STRUCTURE_REQUEST = 'GET_FEE_STRUCTURE_REQUEST';
export const GET_FEE_STRUCTURE_SUCCESS = 'GET_FEE_STRUCTURE_SUCCESS';
export const GET_FEE_STRUCTURE_FAIL = 'GET_FEE_STRUCTURE_FAIL';

export const UPDATE_FEE_STRUCTURE_REQUEST = 'UPDATE_FEE_STRUCTURE_REQUEST';
export const UPDATE_FEE_STRUCTURE_SUCCESS = 'UPDATE_FEE_STRUCTURE_SUCCESS';
export const UPDATE_FEE_STRUCTURE_FAIL = 'UPDATE_FEE_STRUCTURE_FAIL';

export const DELETE_FEE_STRUCTURE_REQUEST = 'DELETE_FEE_STRUCTURE_REQUEST';
export const DELETE_FEE_STRUCTURE_SUCCESS = 'DELETE_FEE_STRUCTURE_SUCCESS';
export const DELETE_FEE_STRUCTURE_FAIL = 'DELETE_FEE_STRUCTURE_FAIL';
