// Constants for creating feedback
export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAILURE = 'CREATE_FEEDBACK_FAILURE';

// Constants for fetching all feedbacks
export const FETCH_ALL_FEEDBACK_REQUEST = 'FETCH_ALL_FEEDBACK_REQUEST';
export const FETCH_ALL_FEEDBACK_SUCCESS = 'FETCH_ALL_FEEDBACK_SUCCESS';
export const FETCH_ALL_FEEDBACK_FAILURE = 'FETCH_ALL_FEEDBACK_FAILURE';

// Constants for fetching a single feedback by ID
export const FETCH_FEEDBACK_REQUEST = 'FETCH_FEEDBACK_REQUEST';
export const FETCH_FEEDBACK_SUCCESS = 'FETCH_FEEDBACK_SUCCESS';
export const FETCH_FEEDBACK_FAILURE = 'FETCH_FEEDBACK_FAILURE';

// Constants for updating feedback
export const UPDATE_FEEDBACK_REQUEST = 'UPDATE_FEEDBACK_REQUEST';
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS';
export const UPDATE_FEEDBACK_FAILURE = 'UPDATE_FEEDBACK_FAILURE';

// Constants for deleting feedback
export const DELETE_FEEDBACK_REQUEST = 'DELETE_FEEDBACK_REQUEST';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAILURE = 'DELETE_FEEDBACK_FAILURE';
