// Filename: constants/leaveConstants.js

export const LEAVE_REQUEST = 'LEAVE_REQUEST';
export const LEAVE_SUCCESS = 'LEAVE_SUCCESS';
export const LEAVE_FAIL = 'LEAVE_FAIL';

export const LEAVE_LIST_REQUEST = 'LEAVE_LIST_REQUEST';
export const LEAVE_LIST_SUCCESS = 'LEAVE_LIST_SUCCESS';
export const LEAVE_LIST_FAIL = 'LEAVE_LIST_FAIL';

export const LEAVE_UPDATE_REQUEST = 'LEAVE_UPDATE_REQUEST';
export const LEAVE_UPDATE_SUCCESS = 'LEAVE_UPDATE_SUCCESS';
export const LEAVE_UPDATE_FAIL = 'LEAVE_UPDATE_FAIL';

export const LEAVE_DELETE_REQUEST = 'LEAVE_DELETE_REQUEST';
export const LEAVE_DELETE_SUCCESS = 'LEAVE_DELETE_SUCCESS';
export const LEAVE_DELETE_FAIL = 'LEAVE_DELETE_FAIL';

export const LEAVE_DETAILS_REQUEST = 'LEAVE_DETAILS_REQUEST';
export const LEAVE_DETAILS_SUCCESS = 'LEAVE_DETAILS_SUCCESS';
export const LEAVE_DETAILS_FAIL = 'LEAVE_DETAILS_FAIL';

export const USER_LEAVE_DETAILS_REQUEST = 'USER_LEAVE_DETAILS_REQUEST';
export const USER_LEAVE_DETAILS_SUCCESS = 'USER_LEAVE_DETAILS_SUCCESS';
export const USER_LEAVE_DETAILS_FAIL = 'USER_LEAVE_DETAILS_FAIL';

export const LEAVE_CREATE_REQUEST = 'LEAVE_CREATE_REQUEST';
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS';
export const LEAVE_CREATE_FAIL = 'LEAVE_CREATE_FAIL';

export const LEAVE_RESET = 'LEAVE_RESET';  // Used to reset the leave form or state
