export const MARKET_AGENT_REGISTER_REQUEST = 'MARKET_AGENT_REGISTER_REQUEST'
export const MARKET_AGENT_REGISTER_SUCCESS = 'MARKET_AGENT_REGISTER_SUCCESS'
export const MARKET_AGENT_REGISTER_FAIL = 'MARKET_AGENT_REGISTER_FAIL'