export const MARKET_LEAD_REGISTER_REQUEST = 'MARKET_LEAD_REGISTER_REQUEST'
export const MARKET_LEAD_REGISTER_SUCCESS = 'MARKET_LEAD_REGISTER_SUCCESS'
export const MARKET_LEAD_REGISTER_FAIL = 'MARKET_LEAD_REGISTER_FAIL'

export const ALL_MARKET_LEAD_REQUEST = 'ALL_MARKET_LEAD_REQUEST'
export const ALL_MARKET_LEAD_SUCCESS = 'ALL_MARKET_LEAD_SUCCESS'
export const ALL_MARKET_LEAD_FAIL = 'ALL_MARKET_LEAD_FAIL'

export const INDIVIDUAL_MARKET_LEAD_REQUEST = 'INDIVIDUAL_MARKET_LEAD_REQUEST'
export const INDIVIDUAL_MARKET_LEAD_SUCCESS = 'INDIVIDUAL_MARKET_LEAD_SUCCESS'
export const INDIVIDUAL_MARKET_LEAD_FAIL = 'INDIVIDUAL_MARKET_LEAD_FAIL'

export const MY_MARKET_LEADS_REQUEST = 'MY_MARKET_LEAD_REQUEST'
export const MY_MARKET_LEADS_SUCCESS = 'MY_MARKET_LEAD_SUCCESS'
export const MY_MARKET_LEADS_FAIL = 'MY_MARKET_LEAD_FAIL'

export const UPDATE_MARKET_LEADS_STATUS_REQUEST = 'UPDATE_MARKET_LEADS_STATUS_REQUEST'
export const UPDATE_MARKET_LEADS_STATUS_SUCCESS = 'UPDATE_MARKET_LEAD_STATUS_SUCCESS_'
export const UPDATE_MARKET_LEADS_STATUS_FAIL = 'UPDATE_MARKET_LEADS_STATUS_FAIL'

// Constants for downloading all marketing leads to Excel
export const DOWNLOAD_ALL_LEADS_EXCEL_REQUEST = 'DOWNLOAD_ALL_LEADS_EXCEL_REQUEST';
export const DOWNLOAD_ALL_LEADS_EXCEL_SUCCESS = 'DOWNLOAD_ALL_LEADS_EXCEL_SUCCESS';
export const DOWNLOAD_ALL_LEADS_EXCEL_FAILURE = 'DOWNLOAD_ALL_LEADS_EXCEL_FAILURE';

// Constants for downloading leads by agent to Excel
export const DOWNLOAD_LEADS_BY_AGENT_EXCEL_REQUEST = 'DOWNLOAD_LEADS_BY_AGENT_EXCEL_REQUEST';
export const DOWNLOAD_LEADS_BY_AGENT_EXCEL_SUCCESS = 'DOWNLOAD_LEADS_BY_AGENT_EXCEL_SUCCESS';
export const DOWNLOAD_LEADS_BY_AGENT_EXCEL_FAILURE = 'DOWNLOAD_LEADS_BY_AGENT_EXCEL_FAILURE';

// Constants for downloading single lead by ID to Excel
export const DOWNLOAD_LEAD_BY_ID_EXCEL_REQUEST = 'DOWNLOAD_LEAD_BY_ID_EXCEL_REQUEST';
export const DOWNLOAD_LEAD_BY_ID_EXCEL_SUCCESS = 'DOWNLOAD_LEAD_BY_ID_EXCEL_SUCCESS';
export const DOWNLOAD_LEAD_BY_ID_EXCEL_FAILURE = 'DOWNLOAD_LEAD_BY_ID_EXCEL_FAILURE';
