// Redux constants for REIMBURSMENTs
export const CREATE_PETTY_CASH_REQUEST = 'CREATE_PETTY_CASH_REQUEST';
export const PETTY_CASH_CREATE_SUCCESS = 'PETTY_CASH_CREATE_SUCCESS';
export const PETTY_CASH_CREATE_FAIL = 'PETTY_CASH_CREATE_FAIL';

export const ALL_PETTY_CASH_REQUEST = 'ALL_PETTY_CASH_REQUEST';
export const ALL_PETTY_CASH_SUCCESS = 'ALL_PETTY_CASH_SUCCESS';
export const ALL_PETTY_CASH_FAIL = 'ALL_PETTY_CASH_FAIL';

export const INDIVIDUAL_PETTY_CASH_REQUEST = 'INDIVIDUAL_PETTY_CASH_REQUEST';
export const INDIVIDUAL_PETTY_CASH_SUCCESS = 'INDIVIDUAL_PETTY_CASH_SUCCESS';
export const INDIVIDUAL_PETTY_CASH_FAIL = 'INDIVIDUAL_PETTY_CASH_FAIL';
