// Redux constants for REIMBURSMENTs
export const CREATE_REIMBURSMENT_REQUEST = 'CREATE_REIMBURSMENT_REQUEST';
export const REIMBURSMENT_CREATE_SUCCESS = 'REIMBURSMENT_CREATE_SUCCESS';
export const REIMBURSMENT_CREATE_FAIL = 'REIMBURSMENT_CREATE_FAIL';

export const ALL_REIMBURSMENTS_REQUEST = 'ALL_REIMBURSMENTS_REQUEST';
export const ALL_REIMBURSMENTS_SUCCESS = 'ALL_REIMBURSMENTS_SUCCESS';
export const ALL_REIMBURSMENTS_FAIL = 'ALL_REIMBURSMENTS_FAIL';

export const INDIVIDUAL_REIMBURSMENT_REQUEST = 'INDIVIDUAL_REIMBURSMENT_REQUEST';
export const INDIVIDUAL_REIMBURSMENT_SUCCESS = 'INDIVIDUAL_REIMBURSMENT_SUCCESS';
export const INDIVIDUAL_REIMBURSMENT_FAIL = 'INDIVIDUAL_REIMBURSMENT_FAIL';
