// Redux constants for requisitions
export const CREATE_REQUISITION_REQUEST = 'CREATE_REQUISITION_REQUEST';
export const REQUISITION_CREATE_SUCCESS = 'REQUISITION_CREATE_SUCCESS';
export const REQUISITION_CREATE_FAIL = 'REQUISITION_CREATE_FAIL';

export const ALL_REQUISITIONS_REQUEST = 'ALL_REQUISITIONS_REQUEST';
export const ALL_REQUISITIONS_SUCCESS = 'ALL_REQUISITIONS_SUCCESS';
export const ALL_REQUISITIONS_FAIL = 'ALL_REQUISITIONS_FAIL';

export const INDIVIDUAL_REQUISITION_REQUEST = 'INDIVIDUAL_REQUISITION_REQUEST';
export const INDIVIDUAL_REQUISITION_SUCCESS = 'INDIVIDUAL_REQUISITION_SUCCESS';
export const INDIVIDUAL_REQUISITION_FAIL = 'INDIVIDUAL_REQUISITION_FAIL';

export const DEPARTMENT_REQUISITION_LIST_REQUEST = 'DEPARTMENT_REQUISITION_LIST_REQUEST';
export const DEPARTMENT_REQUISITION_LIST_SUCCESS = 'DEPARTMENT_REQUISITION_LIST_SUCCESS';
export const DEPARTMENT_REQUISITION_LIST_FAIL = 'DEPARTMENT_REQUISITION_LIST_FAIL';

// src/constants/requisitionConstants.js

export const REQUISITION_APPROVE_REQUEST = 'REQUISITION_APPROVE_REQUEST';
export const REQUISITION_APPROVE_SUCCESS = 'REQUISITION_APPROVE_SUCCESS';
export const REQUISITION_APPROVE_FAIL = 'REQUISITION_APPROVE_FAIL';
