export const ALL_SCHOOLS_REQUEST = 'ALL_SCHOOLS_REQUEST';
export const ALL_SCHOOLS_SUCCESS = 'ALL_SCHOOLS_SUCCESS';
export const ALL_SCHOOLS_FAIL = 'ALL_SCHOOLS_FAIL';
export const ALL_SCHOOLS_RESET = 'ALL_SCHOOLS_RESET'

export const INDIVIDUAL_SCHOOL_REQUEST = 'INDIVIDUAL_SCHOOL_REQUEST';
export const INDIVIDUAL_SCHOOL_SUCCESS = 'INDIVIDUAL_SCHOOL_SUCCESS';
export const INDIVIDUAL_SCHOOL_FAIL = 'INDIVIDUAL_SCHOOL_FAIL';