export const ALL_STUDENTS_REQUEST = 'ALL_STUDENTS_REQUEST';
export const ALL_STUDENTS_SUCCESS = 'ALL_STUDENTS_SUCCESS';
export const ALL_STUDENTS_FAIL = 'ALL_STUDENTS_FAIL';

export const INDIVIDUAL_STUDENT_REQUEST = 'INDIVIDUAL_STUDENT_REQUEST';
export const INDIVIDUAL_STUDENT_SUCCESS = 'INDIVIDUAL_STUDENT_SUCCESS';
export const INDIVIDUAL_STUDENT_FAIL = 'INDIVIDUAL_STUDENT_FAIL';

export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';