// Term Dates Constants
export const TERM_DATES_LIST_REQUEST = 'TERM_DATES_LIST_REQUEST';
export const TERM_DATES_LIST_SUCCESS = 'TERM_DATES_LIST_SUCCESS';
export const TERM_DATES_LIST_FAIL = 'TERM_DATES_LIST_FAIL';

export const TERM_DATE_DETAILS_REQUEST = 'TERM_DATE_DETAILS_REQUEST';
export const TERM_DATE_DETAILS_SUCCESS = 'TERM_DATE_DETAILS_SUCCESS';
export const TERM_DATE_DETAILS_FAIL = 'TERM_DATE_DETAILS_FAIL';

export const TERM_DATE_CREATE_REQUEST = 'TERM_DATE_CREATE_REQUEST';
export const TERM_DATE_CREATE_SUCCESS = 'TERM_DATE_CREATE_SUCCESS';
export const TERM_DATE_CREATE_FAIL = 'TERM_DATE_CREATE_FAIL';
export const TERM_DATE_CREATE_RESET = 'TERM_DATE_CREATE_RESET';

export const TERM_DATE_UPDATE_REQUEST = 'TERM_DATE_UPDATE_REQUEST';
export const TERM_DATE_UPDATE_SUCCESS = 'TERM_DATE_UPDATE_SUCCESS';
export const TERM_DATE_UPDATE_FAIL = 'TERM_DATE_UPDATE_FAIL';
export const TERM_DATE_UPDATE_RESET = 'TERM_DATE_UPDATE_RESET';

export const TERM_DATE_DELETE_REQUEST = 'TERM_DATE_DELETE_REQUEST';
export const TERM_DATE_DELETE_SUCCESS = 'TERM_DATE_DELETE_SUCCESS';
export const TERM_DATE_DELETE_FAIL = 'TERM_DATE_DELETE_FAIL';

// Event Management within a Term Date
export const EVENT_ADD_REQUEST = 'EVENT_ADD_REQUEST';
export const EVENT_ADD_SUCCESS = 'EVENT_ADD_SUCCESS';
export const EVENT_ADD_FAIL = 'EVENT_ADD_FAIL';
export const EVENT_ADD_RESET = 'EVENT_ADD_RESET';

export const EVENT_UPDATE_REQUEST = 'EVENT_UPDATE_REQUEST';
export const EVENT_UPDATE_SUCCESS = 'EVENT_UPDATE_SUCCESS';
export const EVENT_UPDATE_FAIL = 'EVENT_UPDATE_FAIL';
export const EVENT_UPDATE_RESET = 'EVENT_UPDATE_RESET';

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL';
