// Transaction Constants
export const TRANSACTION_CREATE_REQUEST = 'TRANSACTION_CREATE_REQUEST';
export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';
export const TRANSACTION_CREATE_FAIL = 'TRANSACTION_CREATE_FAIL';

export const TRANSACTION_LIST_REQUEST = 'TRANSACTION_LIST_REQUEST';
export const TRANSACTION_LIST_SUCCESS = 'TRANSACTION_LIST_SUCCESS';
export const TRANSACTION_LIST_FAIL = 'TRANSACTION_LIST_FAIL';

export const TRANSACTION_DETAILS_REQUEST = 'TRANSACTION_DETAILS_REQUEST';
export const TRANSACTION_DETAILS_SUCCESS = 'TRANSACTION_DETAILS_SUCCESS';
export const TRANSACTION_DETAILS_FAIL = 'TRANSACTION_DETAILS_FAIL';

export const TRANSACTION_UPDATE_REQUEST = 'TRANSACTION_UPDATE_REQUEST';
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS';
export const TRANSACTION_UPDATE_FAIL = 'TRANSACTION_UPDATE_FAIL';

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST';
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS';
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL';

export const TRANSACTION_CREDIT_ALL_REQUEST = 'TRANSACTION_CREDIT_ALL_REQUEST';
export const TRANSACTION_CREDIT_ALL_SUCCESS = 'TRANSACTION_CREDIT_ALL_SUCCESS';
export const TRANSACTION_CREDIT_ALL_FAIL = 'TRANSACTION_CREDIT_ALL_FAIL';

export const TRANSACTIONS_BY_STUDENT_REQUEST = 'TRANSACTIONS_BY_STUDENT_REQUEST';
export const TRANSACTIONS_BY_STUDENT_SUCCESS = 'TRANSACTIONS_BY_STUDENT_SUCCESS';
export const TRANSACTIONS_BY_STUDENT_FAILURE = 'TRANSACTIONS_BY_STUDENT_FAILURE';

export const GET_ALL_FEE_PAYMENT_TRANSACTIONS_REQUEST = 'GET_ALL_FEE_PAYMENT_TRANSACTIONS_REQUEST';
export const GET_ALL_FEE_PAYMENT_TRANSACTIONS_SUCCESS = 'GET_ALL_FEE_PAYMENT_TRANSACTIONS_SUCCESS';
export const GET_ALL_FEE_PAYMENT_TRANSACTIONS_FAIL = 'GET_ALL_FEE_PAYMENT_TRANSACTIONS_FAIL';

// Redux constants for paying school fees
export const PAY_SCHOOL_FEES_REQUEST = 'PAY_SCHOOL_FEES_REQUEST';
export const PAY_SCHOOL_FEES_SUCCESS = 'PAY_SCHOOL_FEES_SUCCESS';
export const PAY_SCHOOL_FEES_FAILURE = 'PAY_SCHOOL_FEES_FAILURE';
