// Constants for fetching all voteheads
export const VOTEHEAD_LIST_REQUEST = 'VOTEHEAD_LIST_REQUEST';
export const VOTEHEAD_LIST_SUCCESS = 'VOTEHEAD_LIST_SUCCESS';
export const VOTEHEAD_LIST_FAIL = 'VOTEHEAD_LIST_FAIL';

// Constants for fetching a single votehead
export const VOTEHEAD_DETAILS_REQUEST = 'VOTEHEAD_DETAILS_REQUEST';
export const VOTEHEAD_DETAILS_SUCCESS = 'VOTEHEAD_DETAILS_SUCCESS';
export const VOTEHEAD_DETAILS_FAIL = 'VOTEHEAD_DETAILS_FAIL';

// Constants for creating a new votehead
export const VOTEHEAD_CREATE_REQUEST = 'VOTEHEAD_CREATE_REQUEST';
export const VOTEHEAD_CREATE_SUCCESS = 'VOTEHEAD_CREATE_SUCCESS';
export const VOTEHEAD_CREATE_FAIL = 'VOTEHEAD_CREATE_FAIL';
export const VOTEHEAD_CREATE_RESET = 'VOTEHEAD_CREATE_RESET';

// Constants for updating an existing votehead
export const VOTEHEAD_UPDATE_REQUEST = 'VOTEHEAD_UPDATE_REQUEST';
export const VOTEHEAD_UPDATE_SUCCESS = 'VOTEHEAD_UPDATE_SUCCESS';
export const VOTEHEAD_UPDATE_FAIL = 'VOTEHEAD_UPDATE_FAIL';
export const VOTEHEAD_UPDATE_RESET = 'VOTEHEAD_UPDATE_RESET';

// Constants for deleting a votehead
export const VOTEHEAD_DELETE_REQUEST = 'VOTEHEAD_DELETE_REQUEST';
export const VOTEHEAD_DELETE_SUCCESS = 'VOTEHEAD_DELETE_SUCCESS';
export const VOTEHEAD_DELETE_FAIL = 'VOTEHEAD_DELETE_FAIL';
export const VOTEHEAD_DELETE_RESET = 'VOTEHEAD_DELETE_RESET';
